In [1]:
2+2


4

In [8]:
import numpy as np

In [9]:
2+5.7

7.7

In [3]:
mylist = [1,2,3,4]

In [4]:
mylist


[1, 2, 3, 4]

In [5]:
myarr = np.array(mylist)

In [6]:
myarr


array([1, 2, 3, 4])

In [7]:
arr=np.arrange(0,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
arr=np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr=np.arange(0,11,2)

In [11]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [12]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [13]:
arr = np.zeros(4)

In [14]:
arr

array([0., 0., 0., 0.])

In [15]:
arr= np.zeros(3,3)

TypeError: data type not understood

In [16]:
arr=np.zeros((3,3))

In [17]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr=np.ones((5,5))

In [20]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
type(arr)

numpy.ndarray

In [23]:
np.ndim(arr)

2

In [24]:
np.linspace(1,11,4)

array([ 1.        ,  4.33333333,  7.66666667, 11.        ])

In [1]:
arr,spacing=np.linespace(0,1,30, retstep=True)

NameError: name 'np' is not defined

In [2]:
arr, spacing = np.linspace(0,1,20,retstep=True)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
arr, spacing = np.linspace(0,1,20,retstep=True)

In [5]:
spacing

0.05263157894736842

In [10]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [11]:
arr.shape()

TypeError: 'tuple' object is not callable

In [12]:
arr.shape

(20,)

In [13]:
arr=np.linspace(1,10)

In [14]:
arr.shape

(50,)

In [16]:
np.eye(4,k=-0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.06044765, 0.76214872, 0.7170899 , 0.79327748, 0.3206249 ])

In [21]:
np.random.randint(0,20,6)

array([17,  9,  5, 13, 13, 11])

In [22]:
rnd=np.random.randint(0,25,9)

In [23]:
rnd

array([ 3, 13, 19, 21, 10, 12, 14,  0,  6])

In [24]:
rnd.reshape(2,2)

ValueError: cannot reshape array of size 9 into shape (2,2)

In [25]:
rnd.reshape(3,3)

array([[ 3, 13, 19],
       [21, 10, 12],
       [14,  0,  6]])

In [26]:
rnd.max()

21

In [27]:
rnd.min()

0

In [28]:
rnd.argmax()

3

In [29]:
rnd.argmin()

7

In [31]:
rnd.shape

(9,)

In [34]:
np.random.randint(0,25,9).reshape(9,1).shape

(9, 1)

In [35]:
arr[0,10]

IndexError: too many indices for array

In [37]:
arr=np.arange(0,10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr_slice = arr[0:10]

In [45]:
arr_slice

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr_slice[:]=0

In [47]:
arr_slice

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
mat=np.arange(0,25).reshape(5,5)

In [49]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
mat[3,2]

17

In [52]:
mat[:2,:2]

array([[0, 1],
       [5, 6]])

In [56]:
mat[[1,3,5,9,0]]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [57]:
arr=np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [60]:
filter =arr>3

In [62]:
arr[filter]

array([ 4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [65]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])